version: '3'

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD="password"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
